spring.application.name=franquicias-api


# conexion a la DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Accenture_Prueba_Tec_Franquicias;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD